services:
- docker

script:
  - set -e
  - docker build -t circa10a/web-link-tester .
  - docker run -d -p 80:5000 circa10a/web-link-tester
  - sleep 5
  - curl -X POST --data "https://www.github.com" http://localhost/api
  - npm install -g heroku-cli
  - heroku plugins:install heroku-container-registry
  - docker login --username=_ --password=$api_token registry.heroku.com
  - docker build -t registry.heroku.com/web-link-tester/web .
  - docker pushregistry.heroku.com/web-link-tester/web
