language: python
addons:
  ssh_known_hosts: scrapeyour.site
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_626d144bbea6_key -iv $encrypted_626d144bbea6_iv
  -in deploy.enc -out /tmp/deploy -d
- set -e
- docker build -t $docker_username/web-link-tester .
- docker run -d -p 80:80 $docker_username/web-link-tester
- sleep 5
script:
- curl -X POST --data "https://github.com" http://localhost/api
after_script:
- docker login --username=$docker_username --password=$docker_password
- docker push $docker_username/web-link-tester
before_deploy:
  - echo -e "Host scrapeyour.site\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: dev
  script:
  - ssh -i /tmp/deploy core@scrapeyour.site 'docker rm
    -f web-link-tester && docker rmi -f $docker_username/web-link-tester && docker
    run --name web-link-tester -d -p 80:80 $docker_username/web-link-tester'
