language: python
node_js:
  - 'lts/*'
services:
- docker
before_install:
- set -e
- npm install -g npm
- npm -v
- npm install -g heroku-cli
- docker build -t circa10a/web-link-tester .
- docker run -d -p 80:80 circa10a/web-link-tester
- sleep 5
script:
- curl -X POST --data "https://github.com" http://localhost/api
after_script:
deploy:
 provider: script
 skip_cleanup: true
 script:
